[Lua bindings] It was a bad idea to set Tux (the FDtux instance) as a global Lua variable.
This works for Tux because there is only a single instance of FDtux,
but the use of a global var will not work for the instance of the FDnpc
(not yet written) associated with the dialog.
Let's call that insta nce MyNPC. If MyNPC is a global var, and if a node
script launches a dialog with an other NPC, then MyNPC will be overriden...

So instead of a global var, this patch defines Tux as a local upvalue of
each dialog.

Changes adapt_to_FDtux script accordingly.

diff --git a/dialogs/adapt_to_FDtux b/dialogs/adapt_to_FDtux
--- a/dialogs/adapt_to_FDtux
+++ b/dialogs/adapt_to_FDtux
@@ -7,6 +7,22 @@ fi
 
 F=$1
 
+# Check license in header
+
+if [[ `head -17 $F | tail -1` != "-- MA 02111-1307 USA" ]] ; then
+  echo "License header not found. Can not work with this file"
+  exit 1
+fi
+
+# Add global Tux
+
+grep -q "local Tux = FDrpg.get_tux()" $F
+if [[ $? -ne 0 ]] ; then
+  sed -i -e "18 a \\
+\\
+local Tux = FDrpg.get_tux()" $F
+fi
+
 # cfuns
 
 sed -i -e "s/[^:]get_player_name(/Tux:get_player_name(/g" $F
