[l10n] Add make targets to update/pull/push translations hosted on 'freedroid-rpg' project on Transifex:
- make tx-update : Update the .pot files and upload them to TX
- make tx-pull   : Download .po files from TX (use languages defined in
                   LINGUAS)
- make tx-push   : Upload .po files to FX (to be used if there was some
                   modifications to a .po file after downloading it).

A Transifex account, with write access to the TX project, is needed for
those make targets to work.

diff --git a/po/Makefile.am b/po/Makefile.am
--- a/po/Makefile.am
+++ b/po/Makefile.am
@@ -30,3 +30,52 @@ $(UPDATEGMODIRS):
 	$(MAKE) -C $(@:updategmo-%=%) $(AM_MAKEFLAGS) update-gmo
 
 .PHONY: update-gmo-no update-gmo-yes $(UPDATEGMODIRS)
+
+# TX synchronization rules
+# We call subdirs in sequence, to avoid to flood the Transifex server
+# too much
+
+TXTARGETS = tx-update tx-pull tx-push
+TXPROJ    = freedroid-rpg
+TXPROPS   = '{"category":"autoTM"}'
+TXCRED    = $(shell $(top_srcdir)/po/tx-credentials)
+# Create a list of potfiles:
+#  foreach dir in $SUBDIRS - $(foreach ...)
+#    - extract from Makevars the value of the DOMAIN parameter - $(shell ...)
+#    - strip leading/trailing whitespaces - $(strip ...)
+#    - add the dirname as a prefix - $(addprefix ...)
+#    - add a .pot suffix - $(addsuffix ...)
+TXPOTS  = $(foreach dir, $(SUBDIRS), $(addsuffix .pot, $(addprefix $(dir)/, $(strip $(shell gawk -F'=' -e '/^DOMAIN/{ print $$2; }' $(dir)/Makevars)))))
+
+$(TXTARGETS):
+	@test " $(TXCRED)" = " " \
+	 && { \
+	      echo "You do not have a Transifex account"; \
+	      exit 1; \
+	    }; \
+	 for dir in $(SUBDIRS) ; do \
+	     $(MAKE) -C $$dir $@; \
+	 done; \
+	 case $@ in \
+	   tx-update) \
+	     $(mkdir_p) tx; \
+	     msgcat --width=80 --no-wrap --sort-by-file --use-first -o tx/all_in_one.pot $(TXPOTS); \
+	     if test -r tx/all_in_one.pot; then \
+	       if ! tx -q status -r $(TXPROJ).all_in_one 2&>/dev/null; then \
+	         echo "Creating all_in_one"; \
+	         tx -q set --auto-local -r $(TXPROJ).all_in_one "tx/all_in_one-<lang>.po" -t PO --source-lang en --source-file tx/all_in_one.pot --execute; \
+	         if tx -q push -r $(TXPROJ).all_in_one -s; then \
+	           curl_output=`curl -s -L $(TXCRED) -X PUT -d $(TXPROPS) -H "Content-Type: application/json" https://www.transifex.com/api/2/project/$(TXPROJ)/resource/all_in_one;` \
+	           rtn=$$?; \
+	           if test $$rtn -ne 0 -o " $$curl_output" != " OK"; then echo "Warning. Failed to set properties: $$curl_output (error code $$rtn)"; fi; \
+	         fi; \
+	       else \
+	         echo "Updating all_in_one"; \
+	         tx -q push -r $(TXPROJ).all_in_one -s; \
+	       fi; \
+	     fi; \
+	     rm -rf tx; \
+	     ;; \
+	 esac;
+
+.PHONY: $(TXTARGETS)
diff --git a/po/po-src/Rules-others b/po/po-src/Rules-others
--- a/po/po-src/Rules-others
+++ b/po/po-src/Rules-others
@@ -37,3 +37,109 @@ local-install:
 	done
 
 .PHONY: local-install update-pot
+
+#== Transifex synchronization
+
+TXPROJ   = freedroid-rpg
+TXPREFIX = src
+TXPROPS  = '{"category":"src"}'
+TXCRED   = $(shell $(top_srcdir)/po/tx-credentials)
+TXRSRC   = freedroidrpg
+
+# Update the transifex potfiles
+#
+# if the associated resource is not found in the tx config file:
+#   - the resource is created,
+#   - the pot file is pushed,
+#   - and the category is changed.
+# else:
+#   - the pot file is pushed.
+#
+# Note: It is not yet possible to define a resource's category using tx-set
+# (transifex-client version 0.10). We thus directly use the transifex remote
+# API to change it once the resource has been pushed.
+
+tx-update: $(DOMAIN).pot
+	@test " $(TXCRED)" = " " \
+	 && { \
+	      echo "You do not have a Transifex account"; \
+	      exit 1; \
+	    }; \
+	$(mkdir_p) tx; \
+	rsrc=$(TXRSRC); \
+	cp $(DOMAIN).pot tx/$$rsrc.pot; \
+	if test -r tx/$$rsrc.pot; then \
+	  if ! tx -q status -r $(TXPROJ).$(TXPREFIX)-$$rsrc 2&>/dev/null; then \
+	    echo "Creating $(TXPREFIX)-$$rsrc"; \
+	    tx -q set --auto-local -r $(TXPROJ).$(TXPREFIX)-$$rsrc "tx/$$rsrc-<lang>.po" -t PO --source-lang en --source-file tx/$$rsrc.pot --execute; \
+	    if tx -q push -r $(TXPROJ).$(TXPREFIX)-$$rsrc -s; then \
+	      curl_output=`curl -s -L $(TXCRED) -X PUT -d $(TXPROPS) -H "Content-Type: application/json" https://www.transifex.com/api/2/project/$(TXPROJ)/resource/$(TXPREFIX)-$$rsrc;` \
+	      rtn=$$?; \
+	      if test $$rtn -ne 0 -o " $$curl_output" != " OK"; then echo "Warning. Failed to set properties: $$curl_output (error code $$rtn)"; fi; \
+	    fi; \
+	  else \
+	    echo "Updating $(TXPREFIX)-$$rsrc"; \
+	    tx -q push -r $(TXPROJ).$(TXPREFIX)-$$rsrc -s; \
+	  fi; \
+	fi; \
+	rm -rf tx
+
+# Pull the translations from transifex.
+#
+# For each lang:
+# - the translation is fetched from transifex
+# - merged into the game's po file of that lang
+# - merged with the game's pot file (to synchronize comments and file positions)
+#
+# Note: the translated strings of a transifex file will override the
+# translated strings of the game's file.
+
+tx-pull:
+	@test " $(TXCRED)" = " " \
+	 && { \
+	      echo "You do not have a Transifex account"; \
+	      exit 1; \
+	    }; \
+	$(mkdir_p) tx; \
+	catalogs='$(CATALOGS)'; \
+	rsrc=$(TXRSRC); \
+	for cat in $$catalogs; do \
+	  cat=`basename $$cat`; \
+	  lang=`echo $$cat | sed -e 's/\.gmo$$//'`; \
+	  echo "Pulling $$rsrc-$$lang.po from transifex"; \
+	  if tx -q pull -r $(TXPROJ).$(TXPREFIX)-$$rsrc -l $$lang; then \
+	    if test -r tx/$$rsrc-$$lang.po; then \
+	      echo "Merging with $$lang.po"; \
+	      msgcat $(MSGCAT_OPTIONS) --use-first -o $$lang.po tx/$$rsrc-$$lang.po $$lang.po; \
+	    else \
+	      echo "Nothing to merge"; \
+	    fi; \
+	  fi; \
+	  $(MSGMERGE_UPDATE) $(MSGMERGE_OPTIONS) $$lang.po $(DOMAIN).pot; \
+	done; \
+	rm -rf tx
+
+# Push the translations to transifex.
+#
+# For each lang:
+# - the game's po is pushed to transifex
+
+tx-push:
+	@test " $(TXCRED)" = " " \
+	 && { \
+	      echo "You do not have a Transifex account"; \
+	      exit 1; \
+	    }; \
+	$(mkdir_p) tx; \
+	catalogs='$(CATALOGS)'; \
+	rsrc=$(TXRSRC); \
+	for cat in $$catalogs; do \
+	  cat=`basename $$cat`; \
+	  lang=`echo $$cat | sed -e 's/\.gmo$$//'`; \
+	  echo "Pushing $$rsrc-$$lang.po to transifex"; \
+	  cp $$lang.po tx/$$rsrc-$$lang.po; \
+	  tx -q push -r $(TXPROJ).$(TXPREFIX)-$$rsrc -l $$lang -t; \
+	done; \
+	rm -rf tx
+
+.PHONY: tx-update tx-pull tx-push
